/*=========================================
 resume.js
 AI Interview Preparation
=========================================*/

document.addEventListener("DOMContentLoaded", () => {

    const resumeFile = document.getElementById("resumeFile");
    const analyzeBtn = document.getElementById("analyzeBtn");
    const resumeScore = document.getElementById("resumeScore");
    const downloadBtn = document.getElementById("downloadReport");
    const uploadAnotherBtn = document.getElementById("uploadAnother");

    /*==============================
      Analyze Resume
    ==============================*/

    analyzeBtn.addEventListener("click", () => {

        if (!resumeFile.files.length) {

            alert("Please upload your resume first.");

            return;
        }

        const file = resumeFile.files[0];

        if (file.type !== "application/pdf") {

            alert("Only PDF files are allowed.");

            return;
        }

        if (file.size > 5 * 1024 * 1024) {

            alert("Maximum file size is 5 MB.");

            return;
        }

        analyzeBtn.disabled = true;
        analyzeBtn.innerText = "Analyzing...";

        let score = 0;

        const interval = setInterval(() => {

            score++;

            resumeScore.innerText = score + "%";

            if (score >= 85) {

                clearInterval(interval);

                analyzeBtn.disabled = false;
                analyzeBtn.innerText = "Analyze Resume";

                alert("Resume Analysis Completed Successfully!");

                saveHistory(file.name, score);

            }

        }, 20);

    });

    /*==============================
      Save History
    ==============================*/

    function saveHistory(fileName, score) {

        let history =
            JSON.parse(localStorage.getItem("resumeHistory")) || [];

        history.unshift({

            file: fileName,

            score: score + "%",

            date: new Date().toLocaleDateString()

        });

        localStorage.setItem(
            "resumeHistory",
            JSON.stringify(history)
        );

    }

    /*==============================
      Download Report
    ==============================*/

    downloadBtn.addEventListener("click", () => {

        const report = `
AI Resume Analysis Report

Resume Score : ${resumeScore.innerText}

Strengths:
- Good Resume Format
- Strong Projects
- Technical Skills

Weaknesses:
- Add Certifications
- Improve Summary
- Add Internship

Generated by AI Interview Preparation
`;

        const blob = new Blob([report], {
            type: "text/plain"
        });

        const link = document.createElement("a");

        link.href = URL.createObjectURL(blob);

        link.download = "Resume_Report.txt";

        link.click();

    });

    /*==============================
      Upload Another Resume
    ==============================*/

    uploadAnotherBtn.addEventListener("click", () => {

        resumeFile.value = "";

        resumeScore.innerText = "0%";

        alert("Upload a new resume.");

    });

    /*==============================
      Show Selected File
    ==============================*/

    resumeFile.addEventListener("change", () => {

        if (resumeFile.files.length) {

            alert(
                "Selected File: " +
                resumeFile.files[0].name
            );

        }

    });

});